@startuml
sprite $keycloak [48x48/16] {
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@BGGGGGGGGGGGGGGGGGGGGGGB@@@@@@@@@@@@
@@@@@@@@@@&GPPPPPPPPPPPPPPPPPPPPPPPPG&@@@@@@@@@@
@@@@@@@@@&GPPPPPPPPPPPPPPPPPPPPPPPPPPG&@@@@@@@@@
@@@@@@@@#GPPPPPP55555PPPPPPYJ??JPPPPPPP#@@@@@@@@
@@@@@@@GYYYYYY5555YJ?YYYYYY??777?5YYYYYYGBBBBBBB
@@@@@&?::::::~Y55YJJJ~::::~?JJ?777~::^^^^^^^^^^^
@@@@#!.:::::!555YJJ?^::::::~?JJ?777~^^^^^^^^^^^^
@@@B^.:::::7555JJJ?^::::::::^?JJ?777!^^^^^^^^^^^
@@P::::::^J55YJJJ7:::::^^^^^^^7JJ?77?7^^^^^^^^^^
@B:::::::?55Y???7::^^^^^^^^^^^^?YYJ?JJ7^^^^^^^^^
@@P^:^^^:^JYJ?777!^^^^^^^^^^^^?55YJJJ7^^^^^^~~~^
@@@B~:^^^:^!JJJ?77!^^^^^^^^^~J55YJJJ7^^^^~~~~~~~
@@@@#7::::::!JJJ?777~^^^^^^!Y55YJJJ!^^~^^^^~~~~~
@@@@@@?:^^^::~?JJ?777~^^^^!Y55YJ??!^~~~~^~~~~~~~
@@@@@@@GYYYYYY5J???77J555555YJ??J5555555G#######
@@@@@@@@#GPPPPPPYYYJYPPPPPP5YJYYPPPPPPP#@@@@@@@@
@@@@@@@@@&GPPPPPPPPPPPPPPPPPPPPPPPPPPG&@@@@@@@@@
@@@@@@@@@@&GPPPPPPPPPPPPPPPPPPPPPPPPG&@@@@@@@@@@
@@@@@@@@@@@@BGGGGGGGGGGGGGGGGGGGGGGB@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
}


!define DEV_KEYCLOAK(_alias) ENTITY(rectangle,black,keycloak,_alias,DEV KEYCLOAK)
!define DEV_KEYCLOAK(_alias, _label) ENTITY(rectangle,black,keycloak,_label, _alias,DEV KEYCLOAK)
!define DEV_KEYCLOAK(_alias, _label, _shape) ENTITY(_shape,black,keycloak,_label, _alias,DEV KEYCLOAK)
!define DEV_KEYCLOAK(_alias, _label, _shape, _color) ENTITY(_shape,_color,keycloak,_label, _alias,DEV KEYCLOAK)
skinparam folderBackgroundColor<<DEV KEYCLOAK>> White
@enduml
